<a href="https://colab.research.google.com/github/Deekshith1064/Deekshith.K/blob/main/PART_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LIST1

In [4]:
import numpy as np
list1=[1,2,3,4]
array_1=np.array(list1)
array_1

array([1, 2, 3, 4])

LIST2

In [3]:
import numpy as np
list2=[5,6,7,8]
array_2=np.array(list2)
array_2

array([5, 6, 7, 8])

TYPE_LIST

In [5]:
type(list1)

list

In [6]:
type(array_1)

numpy.ndarray

MATHEMATICAL OPERATIONS

In [7]:
print("Multiplication of two arrays:{array_1} and {array_2}",array_1*array_2)
print("Division of two arrays:{array_1} and {array_2}",array_1/array_2)
print("PowerOff of two arrays:{array_1} and {array_2}",array_1**array_2)

Multiplication of two arrays:{array_1} and {array_2} [ 5 12 21 32]
Division of two arrays:{array_1} and {array_2} [0.2        0.33333333 0.42857143 0.5       ]
PowerOff of two arrays:{array_1} and {array_2} [    1    64  2187 65536]


ADDITION OF TWO ARRAYS

In [8]:
result=np.add(array_1,array_2)
result

array([ 6,  8, 10, 12])

np.sin()

In [9]:
np.sin(2)

0.9092974268256817

np.log()

In [10]:
np.log(3)

1.0986122886681098

np.log2()

In [11]:
np.log2(1)

0.0

np.exp()

In [12]:
np.exp(2)

7.38905609893065